#search_rules:
#    start-time: 2020-01-06
#    end-time: 2020-01-10
#    query: snow colorado -is:retweet has:media

search_params:
    max-tweets: 10
    media-fields: url,alt_text
    tweet-fields: id,text,attachments
    user-fields: name,username,profile_image_url,url
    expansions: referenced_tweets.id.author_id,attachments.media_keys

output_params:
    save_file: False
