search_tweets_v2:
  bearer_token: XXXXX
  consumer_key: XXXXX
  consumer_secret: XXXXX
  endpoint: https://api.twitter.com/2/tweets/search/recent

search_params:
    max-tweets: 20
    media-fields: url,alt_text
    tweet-fields: id,text,attachments
    user-fields: name,username,profile_image_url,url
    expansions: referenced_tweets.id.author_id,attachments.media_keys

output_params:
    save_file: False
